# Generated by Django 5.2.1 on 2025-06-03 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='Matrícula do Instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o RG do Instrutor', max_length=15)),
                ('nome', models.CharField(help_text='Informe o nome do Instrutor', max_length=70)),
                ('data_nascimento', models.DateField(blank=True, default=datetime.datetime(2025, 6, 3, 0, 34, 45, 173228, tzinfo=datetime.timezone.utc), help_text='Informe a data de nascimento do Instrutor', null=True)),
                ('telefone', models.CharField(help_text='Informe o telefone do Instrutor', max_length=9)),
                ('ddd', models.CharField(help_text='Informe o DDD do telefone do Instrutor', max_length=3)),
            ],
        ),
    ]
