# Generated by Django 5.2.1 on 2025-06-06 22:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0006_alter_instrutor_data_nascimento'),
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.ForeignKey(blank=True, db_column='titulo_codigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='titulo.titulo'),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 6, 22, 45, 38, 876276, tzinfo=datetime.timezone.utc), help_text='Informe a data de nascimento do Instrutor', null=True),
        ),
    ]
