# Generated by Django 5.2.1 on 2025-06-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiposdeatividade', '0002_alter_tipodeatividade_descricao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoDeAtividade',
            new_name='TiposDeAtividade',
        ),
    ]
