# Generated by Django 5.2.1 on 2025-06-03 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Matrícula do Aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do Aluno', max_length=70)),
                ('data_inicial', models.DateField(default=datetime.datetime(2025, 6, 3, 0, 34, 45, 172228, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial de matrícula do Aluno')),
                ('data_final', models.DateField(blank=True, default=datetime.datetime(2025, 6, 3, 0, 34, 45, 172228, tzinfo=datetime.timezone.utc), help_text='Informe a data final de matrícula do Aluno', null=True)),
            ],
        ),
    ]
