# Generated by Django 5.2.1 on 2025-06-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_data_final_alter_aluno_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_inicial',
            field=models.DateField(help_text='Informe a data inicial de matrícula do Aluno'),
        ),
    ]
