# Generated by Django 5.2.1 on 2025-06-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_alter_aluno_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_final',
            field=models.DateField(blank=True, help_text='Informe a data final de matrícula do Aluno', null=True),
        ),
    ]
