# Generated by Django 5.2.1 on 2025-06-03 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Matrícula do Aluno', primary_key=True, serialize=False)),
                ('horario_aula', models.TimeField(help_text='Informe a hora de início da Turma')),
                ('duracao_aula', models.SmallIntegerField(help_text='Informe a duração em horas da Turma')),
                ('data_inicial', models.DateField(default=datetime.datetime(2025, 6, 3, 0, 34, 45, 175227, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma')),
                ('data_final', models.DateField(blank=True, default=datetime.datetime(2025, 6, 3, 0, 34, 45, 175227, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma', null=True)),
            ],
        ),
    ]
