# Generated by Django 5.2.1 on 2025-06-06 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_alter_turma_data_final_alter_turma_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 6, 21, 25, 13, 557577, tzinfo=datetime.timezone.utc), help_text='Informe a data final da Turma', null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 6, 21, 25, 13, 557577, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
    ]
