# Generated by Django 5.2.1 on 2025-06-06 23:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0008_alter_aluno_data_inicial'),
        ('instrutor', '0008_alter_instrutor_data_nascimento'),
        ('tiposdeatividade', '0003_rename_tipodeatividade_tiposdeatividade'),
        ('turma', '0007_alter_turma_data_final_alter_turma_data_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo_atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='tiposdeatividade.tiposdeatividade'),
        ),
        migrations.AddField(
            model_name='turma',
            name='id_instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='instrutor.instrutor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='matricula_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(blank=True, help_text='Informe a data final da Turma', null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 6, 23, 54, 25, 434439, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
    ]
